name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'  # Specify the Node.js version

      - name: Install dependencies
        run: |
          npm install
          npm install -g @angular/cli

      - name: Build the application
        run: ng build --output-path=dist/koli-frontend

      - name: Deploy to GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=dist/koli-frontend
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
